# Generated by Django 4.1.4 on 2023-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_addmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='')),
                ('eduquali', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
