# Generated by Django 4.1.4 on 2023-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_userprofmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofmodel',
            name='image',
            field=models.ImageField(upload_to='appname/static'),
        ),
        migrations.AlterField(
            model_name='userprofmodel',
            name='resume',
            field=models.FileField(upload_to='appname/static'),
        ),
    ]
