# Generated by Django 4.1.4 on 2023-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_userprofmodel_image_alter_userprofmodel_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofmodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
