# Generated by Django 4.1.4 on 2023-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_userprofmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='applymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25)),
                ('jobtitle', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
